version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"

  rabbit:
    image: rabbitmq:3-management #has the management plugin preinstalled
    ports:
      - "5672:5672" #main port
      - "15672:15672" #admin port

#  cassandra:
#    image: cassandra
#    hostname: cassandra
#    ports:
#      - "9042:9042"
#    volumes:
#      - ./data/cassandra:/var/lib/cassandra

#  redis:
#    image: redis
#    hostname: redis
#    ports:
#      - "6379:6379"
